### ISSUE TITLE
Add dedicated filter to nodes

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/tfgridclient_proxy#129]
filtering based on: 
- nodes belong to farms which have a `dedicated` label on graphql

**Comment by AhmedHanafy725** [comment]
### farms
**Added fields**
- dedicated

**Added queries**
- dedicated: true/false

### nodes
**Added fields**
- dedicated
- rentContractId
- rentedByTwinId

**Added queries**
- dedicated: true/false
- rentable: true/false
- rented_by: twinId (int)
- available_for: twinId (int) 
  this is mainly for capacity planning, so it's used to return the nodes available for a user to deploy on (including/excluding dedicated nodes)

**Comment by mohamedamer453** [comment]
Verified since the current version for [testnet](https://gridproxy.test.grid.tf/version) is `1.4.1` and for [devnet](https://gridproxy.dev.grid.tf/version) `1.5.0` and dedicated nodes support was added to different components and can be checked through [ts_client](https://github.com/threefoldtech/grid3_client_ts/blob/development/scripts/test_node_filters.ts).
