### ISSUE TITLE
Reserving dedicate node is not working

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgridclient_proxy#197]
When you try to reserve a node, reserve button is working and it alerts you that the node is reserved and button changes to unreserve.
![image](https://user-images.githubusercontent.com/109473873/192136744-0e93527c-0835-40d9-bcc5-53ad534d6b49.png)
But when you expand node details or refresh page, reserve button changes back to reserve.
![image](https://user-images.githubusercontent.com/109473873/192136794-c7e2802f-cd55-46e2-8720-4edf25c234f3.png)

[Untitled_ Sep 25, 2022 10_58 AM.webm](https://user-images.githubusercontent.com/109473873/192137104-a73749f4-ee0c-4024-95a5-fd53347974b5.webm)

Also can't rent it in TS Client 
![image](https://user-images.githubusercontent.com/109473873/192136818-2f648f89-5d6d-4ce4-b649-4ab077bc8bcf.png)

And I can't deploy anything on it in weblets 
![image](https://user-images.githubusercontent.com/109473873/192136846-f88bb4c3-c3ed-496a-a66b-54043efafc2f.png)

And Node 31 has no contract in grid proxy
![image](https://user-images.githubusercontent.com/109473873/192136879-28fb2b83-2e07-4766-b437-a2d9d6160327.png)

**Comment by DylanVerstraete** [comment]
Node 31 has an active rent contract: `9351`

**Comment by AhmedHanafy725** [comment]
seems the bug in gridproxy, it only joins the created rent contract into the nodes table, and this contract in the grace period

**Comment by mohamedamer453** [comment]
Verified on qanet. Dashboard v1.2.1, gridproxy v1.6.5 (since there were no rentable nodes available on devnet)

Node reservations are working without any issues.

![image](https://user-images.githubusercontent.com/101194226/201514175-a09a894c-1508-4b5f-9a08-8ce7ec518556.png)

and once the node is rented you can find its rent contract available in the gridproxy.

![image](https://user-images.githubusercontent.com/101194226/201514166-44f597a7-a062-441a-b205-9ac5dfa38591.png)

even when the contract is in grace period it's still marked as rented and the rent info is available from the gridproxy.

![image](https://user-images.githubusercontent.com/101194226/201515196-428979fc-fd97-4e23-b62f-179f27c1832e.png)

![image](https://user-images.githubusercontent.com/101194226/201515232-d4be7b8f-8ee1-49bc-bb0c-e4bed98de42d.png)

![image](https://user-images.githubusercontent.com/101194226/201515214-93c5393b-d8f5-4c85-86cc-47d9d6c82e26.png)
