### ISSUE TITLE
Mainnet Gridproxy does not seem to fully close TCP connections

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/tfgridclient_proxy#205]
Since the mainnet upgrade we notice some large TCP connection amount on the public nodes. After some investigation it seems to be the gridproxy not closing CLOSED TCP connections.

For now we resolved it by restating the mainnet gridproxy.
TCP Socket stats for the server running the gridproxy, you can see it drop after the restart:
![image](https://user-images.githubusercontent.com/88312671/197526193-f267a5fa-4ccd-412b-89ed-5ea3cbb69c79.png)

Same on the mainnet public nodes (caddy):
![image](https://user-images.githubusercontent.com/88312671/197526272-44ca8d4b-47f6-43db-86ac-14b83f2b509f.png)

The issue came to light when we saw the connection amount rising on the public nodes (caddy):
![image](https://user-images.githubusercontent.com/88312671/197526541-d8c00be0-e173-43d9-9a41-4ddc8f99e65a.png)

Current mainnet gridproxy version: v1.5.9

**Comment by coesensbert** [comment]
Around 4300 connections again in two days.

Node running gridproxy:
![image](https://user-images.githubusercontent.com/88312671/198248981-86c115c9-9f7a-45bd-a6af-9e35943ef911.png)

![image](https://user-images.githubusercontent.com/88312671/198249248-5d4d6ce2-6a06-4e1d-9f70-1a994ed829e8.png)

After restarting the gridproxy:
![image](https://user-images.githubusercontent.com/88312671/198249792-993d4301-04a2-4aa8-b21d-40c65e7e6e05.png)

The result on the caddy load balancer of tfchain.grid.tf:
![image](https://user-images.githubusercontent.com/88312671/198249947-56bb3575-9cbd-4976-b2ad-9a60f599f8de.png)

**Comment by coesensbert** [comment]
same situation today, any news on a solution?

**Comment by mariobassem** [comment]
seems like something old that's just appearing now, because the changes in v1.5.9 from v1.5.8 are only in an sql statement and should not be causing this.
it may have something to do with rmb. Investigating now...

**Comment by mohamedamer453** [comment]
Verified on devnet.

I tested it by running the proxy locally and then sending messages over rmb from the proxy, in the older version before the fix the connections weren't closed with each message i sent to a different twin. and by monitoring it from netstat the connections were increasing with each request from rmb.

but after switching to version after the fix and then trying the same flow again and monitoring it from netstat the connections were being closed and with each request to a different twin. except for a certain connection that stayed open for a short period after the request but then it gets closed eventually and after confirming with @MarioBassem it turned out to be normal behavior.


### logs

- Connections after starting the server.

   ![image](https://user-images.githubusercontent.com/101194226/201067335-4b4bca51-df96-4f38-8fdf-3765cca8dc05.png)

- Connections after sending a request to twin 60 from rmb

   ![image](https://user-images.githubusercontent.com/101194226/201067715-834866d2-e047-439d-a4b7-d97df07319b4.png)

- Connections after sending a request to another twin

   ![image](https://user-images.githubusercontent.com/101194226/201068009-6392982d-1d1a-4035-8fc7-5fb9c3e3cdaa.png)

- and after about a minute the connection that stayed open was eventually closed.

   ![image](https://user-images.githubusercontent.com/101194226/201068574-fb57039b-4982-4e92-9a14-65f0f96da5c8.png)


as it can be seen from the screenshots the connections are being closed and the issue was fixed.
