### ISSUE TITLE
Doc: Missing Project description and details 

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfgridclient_proxy#234]
### Description
looking at the docs, there are no (details) about 
- what the project does, how it works, use cases, etc. the doc mainly explains how you can build and run it.
- it mentions TFgridDB repo, but no link is provided.

**Comment by Omarabdul3ziz** [comment]
Daily Updates:
- wrote some docs on the readme file.
- add some extra markdown files under `docs/` with a plan on what it needs.

check the attached pr

**Comment by mohamedamer453** [comment]
Verified on devnet.

The docs were updated starting with the `readme.md` in the repo home, it was updated to include a new table of content with the different sections of the docs.

New sections that were added/updated in the `readme`:

- **About**: includes a brief description about the project and what other projects uses it as a backend.
- **How to use the project**: and the endpoints for each network.
- **Used Technologies & Prerequisites**:  Includes a list of the frameworks and technologies used in the project.
- **Start for Development**: setting up the project for development.
- **Setup for Production**: setting up the for production.

and more docs were added for:

- [Commands](https://github.com/threefoldtech/tfgridclient_proxy/blob/development/docs/commands.md) includes commands that are needed for working on the project (generating docs, starting the proxy, running tests, etc...)
- [Contributions](https://github.com/threefoldtech/tfgridclient_proxy/blob/development/docs/contributions.md) includes information about the project structure and info needed to start contributing to the project. 
- [Explorer](https://github.com/threefoldtech/tfgridclient_proxy/blob/development/docs/explorer.md) include a brief description about the grid explorer and its endpoints.
- [Production](https://github.com/threefoldtech/tfgridclient_proxy/blob/development/docs/production.md) includes information needed for running the grid proxy in production.
- [Setup](https://github.com/threefoldtech/tfgridclient_proxy/blob/development/docs/setup.md) includes info about the perquisites needed to be setup in order to run the proxy.
